/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './watch.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ng2-translate/src/translate.service';
import * as import9 from '../../services/twapi.service';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
export class Wrapper_WatchComponent {
  context:import0.WatchComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.WatchComponent(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_WatchComponent_Host:import2.RenderComponentType = (null as any);
class _View_WatchComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _WatchComponent_0_4:Wrapper_WatchComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_WatchComponent_Host0,renderType_WatchComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('watch-form',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_WatchComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._WatchComponent_0_4 = new Wrapper_WatchComponent(this.parentInjector.get(import8.TranslateService),this.parentInjector.get(import9.TwAPIService),this.parentInjector.get(import10.FormBuilder));
    this._appEl_0.initComponent(this._WatchComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._WatchComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.WatchComponent) && (0 === requestNodeIndex))) { return this._WatchComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._WatchComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_WatchComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_WatchComponent_Host === (null as any))) { (renderType_WatchComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_WatchComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const WatchComponentNgFactory:import12.ComponentFactory<import0.WatchComponent> = new import12.ComponentFactory<import0.WatchComponent>('watch-form',viewFactory_WatchComponent_Host0,import0.WatchComponent);
const styles_WatchComponent:any[] = ([] as any[]);
var renderType_WatchComponent:import2.RenderComponentType = (null as any);
class _View_WatchComponent0 extends import1.AppView<import0.WatchComponent> {
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_WatchComponent0,renderType_WatchComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this.init(([] as any[]),([] as any[]),([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_WatchComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.WatchComponent> {
  if ((renderType_WatchComponent === (null as any))) { (renderType_WatchComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_WatchComponent,{})); }
  return new _View_WatchComponent0(viewUtils,parentInjector,declarationEl);
}