/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './moon-phases.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
export class Wrapper_MoonPhasesComponent {
  context:import0.MoonPhasesComponent;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.MoonPhasesComponent(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_MoonPhasesComponent_Host:import2.RenderComponentType = (null as any);
class _View_MoonPhasesComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MoonPhasesComponent_0_4:Wrapper_MoonPhasesComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MoonPhasesComponent_Host0,renderType_MoonPhasesComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('moon-phases',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MoonPhasesComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MoonPhasesComponent_0_4 = new Wrapper_MoonPhasesComponent(new import8.ElementRef(this._el_0));
    this._appEl_0.initComponent(this._MoonPhasesComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MoonPhasesComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MoonPhasesComponent) && (0 === requestNodeIndex))) { return this._MoonPhasesComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MoonPhasesComponent_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._MoonPhasesComponent_0_4.context.ngAfterViewInit(); } }
  }
}
function viewFactory_MoonPhasesComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MoonPhasesComponent_Host === (null as any))) { (renderType_MoonPhasesComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MoonPhasesComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MoonPhasesComponentNgFactory:import10.ComponentFactory<import0.MoonPhasesComponent> = new import10.ComponentFactory<import0.MoonPhasesComponent>('moon-phases',viewFactory_MoonPhasesComponent_Host0,import0.MoonPhasesComponent);
const styles_MoonPhasesComponent:any[] = ([] as any[]);
var renderType_MoonPhasesComponent:import2.RenderComponentType = (null as any);
class _View_MoonPhasesComponent0 extends import1.AppView<import0.MoonPhasesComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MoonPhasesComponent0,renderType_MoonPhasesComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','moon-phase-container');
    this._text_1 = this.renderer.createText(this._el_0,'\n               ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','moon-mask');
    this._text_3 = this.renderer.createText(this._el_0,'\n               ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','moon-disque');
    this._text_5 = this.renderer.createText(this._el_0,'\n             ',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n             ',(null as any));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_MoonPhasesComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MoonPhasesComponent> {
  if ((renderType_MoonPhasesComponent === (null as any))) { (renderType_MoonPhasesComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_MoonPhasesComponent,{})); }
  return new _View_MoonPhasesComponent0(viewUtils,parentInjector,declarationEl);
}